# figtracer-demo-analysis: v1
"""Tiny editable analysis for ``figtracer demo``. Uses only the Python standard library."""
from html import escape
from pathlib import Path


DATA = [
    ("Control", 12),
    ("Treatment", 19),
    ("Recovery", 15),
]
BAR_COLOR = "#2563eb"
PLOT_TITLE = "Cells recovered by condition"


class DemoFigure:
    """Small figure object with the same ``savefig`` seam as Matplotlib."""

    def __init__(self, data, color, title):
        self.data = data
        self.color = color
        self.title = title

    def get_size_inches(self):
        return (7.2, 3.8)

    def savefig(self, path, **_kwargs):
        Path(path).write_text(self._svg(), encoding="utf-8")

    def _svg(self):
        width, height = 720, 380
        left, top, bottom = 72, 70, 62
        chart_h = height - top - bottom
        gap = 34
        bar_w = (width - left - 42 - gap * (len(self.data) - 1)) / len(self.data)
        peak = max(value for _label, value in self.data) or 1
        parts = [
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 380" role="img">',
            f'<title>{escape(self.title)}</title>',
            '<desc>Bar chart generated by the dependency-free figtracer demo.</desc>',
            '<rect width="720" height="380" rx="16" fill="#ffffff"/>',
            '<text x="36" y="40" font-family="system-ui,sans-serif" font-size="22" '
            f'font-weight="700" fill="#172033">{escape(self.title)}</text>',
            f'<line x1="{left}" y1="{top + chart_h}" x2="690" y2="{top + chart_h}" '
            'stroke="#aab3c2" stroke-width="2"/>',
        ]
        for index, (label, value) in enumerate(self.data):
            x = left + index * (bar_w + gap)
            bar_h = chart_h * value / peak
            y = top + chart_h - bar_h
            parts.extend([
                f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{bar_h:.1f}" '
                f'rx="8" fill="{escape(self.color)}"/>',
                f'<text x="{x + bar_w / 2:.1f}" y="{y - 10:.1f}" text-anchor="middle" '
                f'font-family="system-ui,sans-serif" font-size="16" font-weight="700" '
                f'fill="#172033">{value}</text>',
                f'<text x="{x + bar_w / 2:.1f}" y="{height - 26}" text-anchor="middle" '
                f'font-family="system-ui,sans-serif" font-size="15" fill="#43506a">'
                f'{escape(label)}</text>',
            ])
        parts.append('</svg>')
        return "\n".join(parts) + "\n"


def build_figure():
    """Edit ``DATA``, ``BAR_COLOR`` or ``PLOT_TITLE``, then rerun ``figtracer demo``."""
    return DemoFigure(DATA, BAR_COLOR, PLOT_TITLE)
