"""figtracer doctor bundle — generate a conservative derived QMD for a target share profile.

Phase 2 of the analysis doctor. The doctor *diagnoses* release-readiness; this *generates* the
derived view. It reads the canonical internal QMD and emits a new QMD for `collaborator` or
`publication`, deciding each code chunk from the `share` intent already declared in the notebook:

    include   chunk opted into the profile          -> copied verbatim
    freeze    `share: documentation`, OR stochastic  -> kept but `#| eval: false` (non-executable
              code in the `publication` view             provenance; the blessed object is the boundary)
    exclude   not shared to the profile             -> dropped, with a visible marker

Design invariants:
- **Never edits the source.** Writes a new file only.
- **Gated on the doctor.** Refuses a BLOCKED notebook (unless `--force`) — private paths / undeclared
  intent / executable stochastic-in-publication are resolved *before* bundling.
- **Deterministic + idempotent.** Stamps the source git commit, never a timestamp.
- **Round-trips clean.** The output is itself doctor-READY at the target profile (a test asserts this).

It reuses the doctor's parser wholesale (`parse_qmd`, the `Chunk`/`Document` model, `_share_values`,
`_stochastic_calls`), so it is policy on top of parsing that already exists.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import yaml

from figtracer.analysis_doctor import (
    FENCE_CLOSE,
    PROFILES,
    _share_values,
    _stochastic_calls,
    diagnose,
    parse_qmd,
)

# You derive collaborator/publication views; "internal" IS the canonical source, not a bundle target.
DERIVABLE = tuple(p for p in PROFILES if p != "internal")
_EVAL_OPTION = re.compile(r"^\s*#\|\s*eval\s*:", re.IGNORECASE)
_HEADER_EVAL = re.compile(r",\s*eval\s*=\s*[^,}]+", re.IGNORECASE)


def _effective_share(doc, chunk) -> set[str]:
    """A chunk's share intent: its own `#| share:` if present, else the notebook default."""
    if "share" in chunk.options:
        return _share_values(chunk.options.get("share"))
    return _share_values(doc.analysis.get("share"))


def decide(doc, chunk, profile: str) -> tuple[str, str]:
    """Fate of one chunk in the derived view: (action, reason). Conservative — when a chunk is
    not clearly shared to the profile it is excluded, never silently kept."""
    eff = _effective_share(doc, chunk)
    if "documentation" in eff:
        return "freeze", "share: documentation — retained as non-executable provenance"
    if profile not in eff:
        return "exclude", f"not shared to '{profile}'"
    if profile == "publication":
        stoch = _stochastic_calls(chunk)
        if stoch:
            return "freeze", (f"stochastic ({', '.join(stoch)}) frozen for publication — "
                              f"the derived view loads the blessed object instead")
    return "include", f"shared to '{profile}'"


def _chunk_close(lines: list[str], open_idx: int) -> int:
    j = open_idx + 1
    while j < len(lines) and not FENCE_CLOSE.match(lines[j]):
        j += 1
    return min(j, len(lines) - 1)


def _frontmatter_span(lines: list[str]) -> tuple[int, int] | None:
    if not lines or lines[0].strip() != "---":
        return None
    for k in range(1, len(lines)):
        if lines[k].strip() == "---":
            return (0, k)
    return None


def _git_commit(path) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=str(Path(path).resolve().parent),
            text=True, stderr=subprocess.DEVNULL).strip()
        return out or None
    except Exception:
        return None


def _frontmatter_lines(doc, profile: str, src_name: str, commit: str | None) -> list[str]:
    fm = dict(doc.frontmatter)
    analysis = dict(fm["analysis"]) if isinstance(fm.get("analysis"), dict) else {}
    analysis["share"] = [profile]                       # the derived file IS this one view
    fm["analysis"] = analysis
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).rstrip("\n")
    stamp = f" @ {commit}" if commit else ""
    return (
        ["---", *body.splitlines(), "---", ""]
        + [f"<!-- Generated by `figtracer doctor bundle` from {src_name}{stamp} for the "
           f"'{profile}' view. Do NOT edit — regenerate from the internal source. -->", ""]
    )


def _freeze_chunk(opening: str, body: list[str], closing: str) -> list[str]:
    """Return a chunk whose effective Quarto ``eval`` option is always false.

    Quarto uses the last duplicate YAML key, so merely prepending ``eval: false``
    is unsafe when the source already declares ``eval: true``.  Normalize the
    leading option block and legacy fence option before inserting one canonical
    non-executable value.
    """
    opening = _HEADER_EVAL.sub("", opening)
    leading_blanks: list[str] = []
    i = 0
    while i < len(body) and not body[i].strip():
        leading_blanks.append(body[i])
        i += 1

    options: list[str] = []
    while i < len(body) and body[i].lstrip().startswith("#|"):
        if not _EVAL_OPTION.match(body[i]):
            options.append(body[i])
        i += 1

    return [opening, *leading_blanks, "#| eval: false", *options, *body[i:], closing]


def generate(src, profile: str) -> tuple[str, dict]:
    """Build the derived QMD text + an audit summary. Pure — writes nothing."""
    if profile not in DERIVABLE:
        raise ValueError(f"bundle profile must be one of {DERIVABLE} (got {profile!r})")
    doc, _ = parse_qmd(Path(src))
    lines = doc.lines
    commit = _git_commit(src)
    fm_span = _frontmatter_span(lines)

    out: list[str] = _frontmatter_lines(doc, profile, Path(src).name, commit)
    by_open = {c.start_line - 1: c for c in doc.chunks}
    per_chunk: list[dict] = []

    i = (fm_span[1] + 1) if fm_span else 0
    while i < len(lines):
        chunk = by_open.get(i)
        if chunk is None:
            out.append(lines[i])
            i += 1
            continue
        close = _chunk_close(lines, i)
        action, reason = decide(doc, chunk, profile)
        label = chunk.label or f"unlabelled@{chunk.start_line}"
        per_chunk.append({"label": chunk.label, "action": action, "reason": reason})
        if action == "include":
            out.extend(lines[i:close + 1])
        elif action == "freeze":
            out.append(f"<!-- figtracer: frozen — {reason} -->")
            out.extend(_freeze_chunk(lines[i], lines[i + 1:close], lines[close]))
        else:  # exclude
            out.append(f"<!-- figtracer: omitted chunk '{label}' — {reason} -->")
        i = close + 1

    text = "\n".join(out).rstrip("\n") + "\n"
    summary = {
        "schema_version": 1,
        "tool": "figtracer.bundle",
        "source": str(Path(src).resolve()),
        "profile": profile,
        "source_git_commit": commit,
        "counts": {a: sum(c["action"] == a for c in per_chunk)
                   for a in ("include", "freeze", "exclude")},
        "chunks": per_chunk,
    }
    return text, summary


def run(args) -> int:
    src = Path(args.src).expanduser()
    if not src.is_file() or src.suffix.lower() != ".qmd":
        print(f"bundle: not a QMD file: {src}")
        return 2
    out_path = Path(args.out).expanduser() if args.out else src.with_suffix(
        f".{args.profile}.qmd"
    )
    if src.resolve() == out_path.resolve():
        print("bundle: --out must be different from the canonical source QMD")
        return 2

    # Gate: don't derive a view from a notebook the doctor blocks at this profile.
    report = diagnose(src, profile=args.profile)
    if report["status"] == "BLOCKED" and not args.force:
        print(f"bundle: doctor BLOCKED {src.name} at profile '{args.profile}' — resolve first "
              f"(or --force). Blocking findings:")
        for f in report["findings"]:
            if f["level"] == "ERROR":
                loc = f":{f['line']}" if f.get("line") else ""
                print(f"  {f['rule_id']} {Path(f['path']).name}{loc}: {f['message']}")
        return 1

    text, summary = generate(src, args.profile)

    if args.json:
        print(json.dumps(summary, indent=2))
    if getattr(args, "dry_run", False):
        c = summary["counts"]
        print(f"bundle (dry run): {src.name} -> {out_path.name}  "
              f"[{c['include']} included, {c['freeze']} frozen, {c['exclude']} excluded]")
        return 0

    out_path.write_text(text, encoding="utf-8")
    c = summary["counts"]
    print(f"bundle: wrote {out_path}  "
          f"[{c['include']} included, {c['freeze']} frozen, {c['exclude']} excluded]")
    return 0
