"""A zero-configuration, dependency-free demonstration of the figure-to-note loop.

``figtracer demo`` creates a tiny editable analysis, saves its SVG through the real
``figtracer.savefig`` manifest path, and owns one marked block in a Markdown lab
note. Re-running reads the existing analysis and replaces that block in place.
"""
from __future__ import annotations

import argparse
import re
import runpy
import sys
from pathlib import Path

from figtracer.savefig import savefig


ANALYSIS_SENTINEL = "# figtracer-demo-analysis: v1"
FIGURE_TITLE = "demo_cell_counts"
BLOCK_START = f"<!-- figtracer:{FIGURE_TITLE} START -->"
BLOCK_END = f"<!-- figtracer:{FIGURE_TITLE} END -->"

ANALYSIS_TEMPLATE = '''# figtracer-demo-analysis: v1
"""Tiny editable analysis for ``figtracer demo``. Uses only the Python standard library."""
from html import escape
from pathlib import Path


DATA = [
    ("Control", 12),
    ("Treatment", 19),
    ("Recovery", 15),
]
BAR_COLOR = "#2563eb"
PLOT_TITLE = "Cells recovered by condition"


class DemoFigure:
    """Small figure object with the same ``savefig`` seam as Matplotlib."""

    def __init__(self, data, color, title):
        self.data = data
        self.color = color
        self.title = title

    def get_size_inches(self):
        return (7.2, 3.8)

    def savefig(self, path, **_kwargs):
        Path(path).write_text(self._svg(), encoding="utf-8")

    def _svg(self):
        width, height = 720, 380
        left, top, bottom = 72, 70, 62
        chart_h = height - top - bottom
        gap = 34
        bar_w = (width - left - 42 - gap * (len(self.data) - 1)) / len(self.data)
        peak = max(value for _label, value in self.data) or 1
        parts = [
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 380" role="img">',
            f'<title>{escape(self.title)}</title>',
            '<desc>Bar chart generated by the dependency-free figtracer demo.</desc>',
            '<rect width="720" height="380" rx="16" fill="#ffffff"/>',
            '<text x="36" y="40" font-family="system-ui,sans-serif" font-size="22" '
            f'font-weight="700" fill="#172033">{escape(self.title)}</text>',
            f'<line x1="{left}" y1="{top + chart_h}" x2="690" y2="{top + chart_h}" '
            'stroke="#aab3c2" stroke-width="2"/>',
        ]
        for index, (label, value) in enumerate(self.data):
            x = left + index * (bar_w + gap)
            bar_h = chart_h * value / peak
            y = top + chart_h - bar_h
            parts.extend([
                f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{bar_h:.1f}" '
                f'rx="8" fill="{escape(self.color)}"/>',
                f'<text x="{x + bar_w / 2:.1f}" y="{y - 10:.1f}" text-anchor="middle" '
                f'font-family="system-ui,sans-serif" font-size="16" font-weight="700" '
                f'fill="#172033">{value}</text>',
                f'<text x="{x + bar_w / 2:.1f}" y="{height - 26}" text-anchor="middle" '
                f'font-family="system-ui,sans-serif" font-size="15" fill="#43506a">'
                f'{escape(label)}</text>',
            ])
        parts.append('</svg>')
        return "\\n".join(parts) + "\\n"


def build_figure():
    """Edit ``DATA``, ``BAR_COLOR`` or ``PLOT_TITLE``, then rerun ``figtracer demo``."""
    return DemoFigure(DATA, BAR_COLOR, PLOT_TITLE)
'''

DEMO_README = """# Your figtracer demo

Open `Lab note.md`. It contains a real SVG figure plus the manifest record that
connects it to `analysis.py`.

To see the living-note loop:

1. Edit `DATA`, `BAR_COLOR`, or `PLOT_TITLE` in `analysis.py`.
2. From the parent directory, rerun `figtracer demo --out <this-folder>`.
3. Reopen `Lab note.md`: the existing figure block is updated in place, never duplicated.

The rest of the note is ordinary Markdown and remains yours to edit.
"""

NOTE_INTRO = """# Demo lab note

This paragraph is ordinary Markdown. figtracer only updates the marked figure block below.

"""


def _load_figure(analysis_path: Path):
    source = analysis_path.read_text(encoding="utf-8")
    if ANALYSIS_SENTINEL not in source.splitlines()[:3]:
        raise ValueError(
            f"refusing to execute {analysis_path}: it is not a figtracer demo analysis"
        )
    try:
        namespace = runpy.run_path(str(analysis_path))
        builder = namespace["build_figure"]
        figure = builder()
    except Exception as exc:
        raise RuntimeError(f"could not run {analysis_path.name}: {exc}") from exc
    if not hasattr(figure, "savefig"):
        raise ValueError("analysis.py build_figure() must return an object with savefig()")
    return figure


def _note_block(record: dict, display_title: str) -> str:
    figure_path = (Path("outputs") / record["rel_path"]).as_posix()
    commit = record.get("git_commit") or "not in a git repository yet"
    return (
        f"{BLOCK_START}\n"
        f"## Figure: {display_title}\n\n"
        f"![{display_title}]({figure_path})\n\n"
        f"_Updated {record['saved_at']} from `analysis.py`._\n\n"
        "**Provenance**\n\n"
        "| figure | analysis source | manifest | git commit |\n"
        "|---|---|---|---|\n"
        f"| `{FIGURE_TITLE}` | `analysis.py` | `outputs/MANIFEST.jsonl` | `{commit}` |\n"
        f"{BLOCK_END}"
    )


def _upsert_note(note_path: Path, block: str) -> str:
    existing = note_path.read_text(encoding="utf-8") if note_path.exists() else NOTE_INTRO
    pattern = re.compile(re.escape(BLOCK_START) + r".*?" + re.escape(BLOCK_END), re.DOTALL)
    if pattern.search(existing):
        updated = pattern.sub(lambda _match: block, existing, count=1)
        action = "updated"
    else:
        separator = "" if not existing or existing.endswith("\n\n") else "\n\n"
        updated = existing + separator + block + "\n"
        action = "appended"
    note_path.write_text(updated, encoding="utf-8")
    return action


def run_demo(out_dir: str | Path = "figtracer-demo") -> dict:
    """Create or update one self-contained demo and return its artifact paths."""
    root = Path(out_dir).expanduser().resolve()
    if root.exists() and not root.is_dir():
        raise ValueError(f"output path exists and is not a directory: {root}")
    root.mkdir(parents=True, exist_ok=True)

    analysis_path = root / "analysis.py"
    analysis_created = not analysis_path.exists()
    if analysis_created:
        analysis_path.write_text(ANALYSIS_TEMPLATE, encoding="utf-8")

    readme_path = root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(DEMO_README, encoding="utf-8")

    figure = _load_figure(analysis_path)
    outputs = root / "outputs"
    record = savefig(
        figure,
        title=FIGURE_TITLE,
        format="svg",
        outputs=str(outputs),
        notebook="analysis.py",
    )
    display_title = str(getattr(figure, "title", "Cells recovered by condition"))
    note_path = root / "Lab note.md"
    note_action = _upsert_note(note_path, _note_block(record, display_title))

    return {
        "root": root,
        "analysis": analysis_path,
        "analysis_created": analysis_created,
        "figure": outputs / record["rel_path"],
        "manifest": outputs / "MANIFEST.jsonl",
        "note": note_path,
        "note_action": note_action,
        "record": record,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="figtracer demo",
        description="Build a zero-config analysis -> figure -> MANIFEST -> Markdown-note demo.",
    )
    parser.add_argument(
        "-o", "--out", default="figtracer-demo",
        help="demo folder to create or update (default: ./figtracer-demo)",
    )
    args = parser.parse_args(argv)
    try:
        result = run_demo(args.out)
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"figtracer demo: {exc}", file=sys.stderr)
        return 1

    print("figtracer demo · ready")
    print(f"  folder   : {result['root']}")
    print(f"  analysis : {result['analysis'].name} "
          f"({'created' if result['analysis_created'] else 'kept your edits'})")
    print(f"  figure   : {result['figure'].relative_to(result['root'])}")
    print(f"  manifest : {result['manifest'].relative_to(result['root'])}")
    print(f"  note     : {result['note'].name} ({result['note_action']} figure block)")
    print("\nOpen 'Lab note.md'. Then edit analysis.py and rerun this command; the")
    print("same note block updates in place instead of being pasted again.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
