"""`labkit index --project DEMO` — regenerate the project's Mission Control dashboard note
from every experiment's frontmatter. The visible glue; no Obsidian plugin required."""
from __future__ import annotations

import glob
import json
import os
from datetime import datetime

from . import config

_STATUS_ORDER = ["planning", "staining", "acquired", "analysing", "done", "blocked"]


def _collect(project_cfg: dict) -> list[dict]:
    """One row per experiment_id. An experiment may span several notes — a hub note plus
    per-lineage/compartment notes that carry only the experiment_id to link them (the lab's
    'split a big experiment by lineage' convention). Prefer the current explicit/folder-note
    hub, then the legacy `<exp_id>.md`, so Mission Control agrees with ``figtracer sync``."""
    vault_exp_dir = os.path.join(project_cfg["_vault_root"], project_cfg["vault_dir"])
    by_id: dict[str, dict] = {}
    for note in glob.glob(os.path.join(vault_exp_dir, "*", "*.md")):
        fm = config.read_frontmatter(note)
        eid = fm.get("experiment_id")
        if not eid:
            continue
        fm["_note"] = note
        prev = by_id.get(eid)
        if prev is None or _hub_rank(fm, str(eid)) < _hub_rank(prev, str(eid)):
            by_id[eid] = fm
        elif _hub_rank(fm, str(eid)) == _hub_rank(prev, str(eid)) \
                and not prev.get("title") and fm.get("title"):
            by_id[eid] = fm                      # else prefer the one carrying real metadata
    return sorted(by_id.values(), key=lambda r: str(r.get("experiment_id")))


def _hub_rank(fm: dict, eid: str) -> tuple[bool, bool, bool]:
    path = fm["_note"]
    stem = os.path.splitext(os.path.basename(path))[0]
    folder = os.path.basename(os.path.dirname(path))
    return (
        str(fm.get("role", "")).strip().lower() != "hub",
        stem != folder,
        stem != eid,
    )


def _table(rows: list[dict]) -> str:
    head = ("| Experiment | Title | Status | Platform | Samples | Updated | Links |\n"
            "|---|---|---|---|---|---|---|")
    lines = [head]
    for r in rows:
        eid = r.get("experiment_id", "")
        note_stem = os.path.splitext(os.path.basename(r.get("_note", "")))[0] or str(eid)
        note_link = f"[[{note_stem}]]"
        links = note_link
        if r.get("panel"):
            links += f" · panel: [[{r['panel']}]]"
        samples = r.get("samples") or []
        nsamp = len(samples) if isinstance(samples, list) else samples
        lines.append("| {eid} | {title} | `{status}` | {plat} | {ns} | {upd} | {links} |".format(
            eid=note_link, title=r.get("title", ""), status=r.get("status", "?"),
            plat=r.get("platform", ""), ns=nsamp, upd=r.get("updated", ""), links=links))
    return "\n".join(lines)


def rebuild(project: str, cfg: dict | None = None, stamp: str | None = None) -> dict:
    p = config.project(project, cfg)
    rows = _collect(p)
    by_status = {s: sum(1 for r in rows if r.get("status") == s) for s in _STATUS_ORDER}
    active = [r for r in rows if r.get("status") not in ("done", "blocked")]

    when = stamp or datetime.now().strftime("%Y-%m-%d %H:%M")
    body = [
        f"# {p.get('title', project)} — Mission Control",
        "",
        f"_Auto-generated by `labkit index` · {when} · {len(rows)} "
        f"experiment{'s' if len(rows) != 1 else ''}_",
        "",
        "**Standing context:** " + p.get("context", "").strip(),
        "",
        "**Status:** " + "  ".join(f"{s} {by_status[s]}" for s in _STATUS_ORDER if by_status[s]),
        "",
        "## Active experiments",
        _table(active) if active else "_none_",
        "",
        "## All experiments",
        _table(rows) if rows else "_none — run `labkit new --project "
        + project + " \"title\"`_",
        "",
        "## Related",
        "  ".join(p.get("related", [])) or "_none_",
        "",
    ]
    dash_path = os.path.join(p["_vault_root"], p["dashboard"])
    os.makedirs(os.path.dirname(dash_path), exist_ok=True)
    with open(dash_path, "w") as fh:
        fh.write("\n".join(body))
    return {"dashboard": dash_path, "n_experiments": len(rows), "active": len(active)}


def run(args) -> int:
    cfg = config.load(args.config) if args.config else None
    print(json.dumps(rebuild(args.project, cfg=cfg), indent=2))
    return 0
